version: '3'
services:
  redis:
    image: 0778m/project
  web:
    depends_on: 
      - redis
    build: .
    ports:
      - "3000:8080"
    environment:
      REDIS_HOST : redis
      REDIS_PORT : 6379
    volumes : 
      - "/data"