# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Do not pay attention to this parameter
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vm.provider :virtualbox do |vb|
        config.vbguest.auto_update = false
      end
    end
  
    # Define the VM
    config.vm.define "redis_server" do |server|
      # Specify the Vagrant box to use
      server.vm.box = "hashicorp/bionic64"
      config.vm.synced_folder "../continuous_testing", "/home/continuous_testing"
      #config.vm.synced_folder "../userapi", "/home/userapi"
      config.vm.network "forwarded_port", guest: 80, host: 8080
      # Specify the VM specs when using the Virtualbox provisioner
      server.vm.provider "virtualbox" do |vb|
        vb.name =  "redis.server.local"
        # VM RAM in MB
        vb.memory = 2048
        # VM CPUs
        vb.cpus = 1
      end
      config.vm.provider "vmware_desktop" do |vmware|
        vmware.vmx["memsize"] = "2048"
        vmware.vmx["numvcpus"] = "1"
      end
    end
    
    # Start provisioning
    #$script = <<-SCRIPT
    #echo I am provisioning ...
    #date > /etc/vagrant_provisioned_at
    #SCRIPT
  
  
    #config.vm.provision "shell",
     # inline: $script

  # Use Vagrant Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "playbooks/run.yml"
    # Only run the roles with these tags
    ansible.tags = "install"
  end
  
  end
  