name: Deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./continuous_testing


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "proj-devops" #Must be unique in Heroku
          heroku_email: "avalidzhanova@yahoo.fr"
          usedocker: true